export const NAV_EDITORIAS = [
  "Cidadania",
  "Comércio",
  "Notícias",
  "Política",
  "Saúde",
  "Colunistas",
  "Veículos",
  "Imóveis",
  "Eventos",
  "Fala Povo",
];

export const COUNCILORS = [
  "Aerton Grande - União Brasil",
  "Cabo Rodrigo - PL",
  "Dato do Ônibus - União Brasil",
  "Dean Guimarães - PSD",
  "Dra. Cristina Mutran - MDB",
  "Fernando Henrique - PL",
  "Ilker Moraes - MDB",
  "Jocenilson Souza - PRD",
  "Maiana Stringari - PDT",
  "Marcelo Alves - PT",
  "Márcio do São Félix - PSDB",
  "Marcos Andrade - PSD",
  "Marcos Paulo da Agricultura - PDT",
  "Orlando Elias - PSB",
  "Pacheco - PL",
  "Pastor Ronisteu - PL",
  "Pedrinho Corrêa - PRD",
  "Priscila Veloso - PSD",
  "Ronaldo da 33 - PDT",
  "Ubirajara Sompré - MDB",
  "Vanda Américo - União Brasil",
];

export const PARA_CITIES = [
  "Abaetetuba",
  "Abel Figueiredo",
  "Acará",
  "Água Azul do Norte",
  "Altamira",
  "Ananindeua",
  "Belém",
  "Bom Jesus do Tocantins",
  "Bragança",
  "Breu Branco",
  "Canaã dos Carajás",
  "Castanhal",
  "Conceição do Araguaia",
  "Curionópolis",
  "Dom Eliseu",
  "Eldorado do Carajás",
  "Goianésia do Pará",
  "Itaituba",
  "Itupiranga",
  "Marabá",
  "Medicilândia",
  "Nova Ipixuna",
  "Novo Repartimento",
  "Pacajá",
  "Paragominas",
  "Parauapebas",
  "Redenção",
  "Rondon do Pará",
  "Salinópolis",
  "Santarém",
  "São Domingos do Araguaia",
  "São Félix do Xingu",
  "São João do Araguaia",
  "Tailândia",
  "Tucuruí",
  "Xinguara",
];

export const BRAZIL_STATES = [
  "Acre",
  "Alagoas",
  "Amapá",
  "Amazonas",
  "Bahia",
  "Ceará",
  "Distrito Federal",
  "Espírito Santo",
  "Goiás",
  "Maranhão",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Pará",
  "Paraíba",
  "Paraná",
  "Pernambuco",
  "Piauí",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondônia",
  "Roraima",
  "Santa Catarina",
  "São Paulo",
  "Sergipe",
  "Tocantins",
];

export const HOME_ARTICLES = [
  {
    title: "Famílias marabaenses revivem hábitos de economia alimentar",
    editorial: "Cidadania",
    excerpt:
      "População reclama da alta dos alimentos e relembra práticas tradicionais para reduzir desperdícios.",
    href: "/colunistas/da-redacao",
  },
  {
    title: "Prefeito Toni Cunha recebe novos veículos de comunicação",
    editorial: "Política",
    excerpt:
      "Poder Executivo e Legislativo destacam o papel do jornalismo responsável para o desenvolvimento local.",
    href: "/colunistas/da-redacao",
  },
  {
    title: "Pesquisa popular sobre desempenho da Câmara em 2025",
    editorial: "Notícias",
    excerpt:
      "Enquete aberta para avaliação da população sobre projetos de lei e destaque parlamentar.",
    href: "/#enquete",
  },
];
