export const NAV_EDITORIAS = [
  "Cidadania",
  "Comércio",
  "Notícias",
  "Política",
  "Saúde",
  "Empregos",
  "Colunistas",
  "Veículos",
  "Imóveis",
  "Eventos",
  "Fala Povo",
];

export const COUNCILOR_DETAILS = [
  { name: "Aerton Grande - União Brasil", fullName: "Aerton Lima da Cruz" },
  { name: "Cabo Rodrigo - PL", fullName: "Rodrigo Lima da Silva" },
  {
    name: "Dato do Ônibus - União Brasil",
    fullName: "Deodato do Espírito Santo",
  },
  { name: "Dean Guimarães - PSD", fullName: "Claudean Pereira Guimarães" },
  {
    name: "Dra. Cristina Mutran - MDB",
    fullName: "Maria Cristina Coimbra Mutran",
  },
  {
    name: "Fernando Henrique - PL",
    fullName: "Fernando Henrique Pereira da Silva",
  },
  { name: "Ilker Moraes - MDB", fullName: "Ilker Moraes Ferreira" },
  { name: "Jocenilson Souza - PRD", fullName: "Jocenilson Silva Souza" },
  {
    name: "Maiana Stringari - PDT",
    fullName: "Maiana Clara Rodrigues Stringari",
  },
  { name: "Marcelo Alves - PT", fullName: "Marcelo Alves dos Santos" },
  {
    name: "Márcio do São Félix - PSDB",
    fullName: "Antônio Márcio Farias Gonçalves",
  },
  { name: "Marcos Andrade - PSD", fullName: "Marcos Almeida Sousa de Andrade" },
  {
    name: "Marcos Paulo da Agricultura - PDT",
    fullName: "Marcos Paulo E. Pereira",
  },
  { name: "Orlando Elias - PSB", fullName: "Orlando da Silva Elias" },
  { name: "Pacheco - PL", fullName: "Jimmyson Mesquita Pacheco" },
  { name: "Pastor Ronisteu - PL", fullName: "Ronisteu da Silva Araújo" },
  { name: "Pedrinho Corrêa - PRD", fullName: "Pedro Corrêa Lima" },
  { name: "Priscila Veloso - PSD", fullName: "Priscila Duarte Veloso Silva" },
  { name: "Ronaldo da 33 - PDT", fullName: "Ronaldo Alves Araújo" },
  { name: "Ubirajara Sompré - MDB", fullName: "Ubirajara Nazareno Sompré" },
  {
    name: "Vanda Américo - União Brasil",
    fullName: "Vanda Régia Américo Gomes",
  },
];

export const COUNCILORS = COUNCILOR_DETAILS.map((councilor) => councilor.name);

export const PARA_CITIES = [
  "Abaetetuba",
  "Abel Figueiredo",
  "Acará",
  "Água Azul do Norte",
  "Altamira",
  "Ananindeua",
  "Belém",
  "Bom Jesus do Tocantins",
  "Bragança",
  "Breu Branco",
  "Canaã dos Carajás",
  "Castanhal",
  "Conceição do Araguaia",
  "Curionópolis",
  "Dom Eliseu",
  "Eldorado do Carajás",
  "Goianésia do Pará",
  "Itaituba",
  "Itupiranga",
  "Marabá",
  "Medicilândia",
  "Nova Ipixuna",
  "Novo Repartimento",
  "Pacajá",
  "Paragominas",
  "Parauapebas",
  "Redenção",
  "Rondon do Pará",
  "Salinópolis",
  "Santarém",
  "São Domingos do Araguaia",
  "São Félix do Xingu",
  "São João do Araguaia",
  "Tailândia",
  "Tucuruí",
  "Xinguara",
];

export const BRAZIL_STATES = [
  "Acre",
  "Alagoas",
  "Amapá",
  "Amazonas",
  "Bahia",
  "Ceará",
  "Distrito Federal",
  "Espírito Santo",
  "Goiás",
  "Maranhão",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Pará",
  "Paraíba",
  "Paraná",
  "Pernambuco",
  "Piauí",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondônia",
  "Roraima",
  "Santa Catarina",
  "São Paulo",
  "Sergipe",
  "Tocantins",
];

export const HOME_ARTICLES = [
  {
    title: "Famílias marabaenses revivem hábitos de economia alimentar",
    editorial: "Cidadania",
    excerpt:
      "População reclama da alta dos alimentos e relembra práticas tradicionais para reduzir desperdícios.",
    href: "/colunistas/da-redacao",
  },
  {
    title: "Prefeito Toni Cunha recebe novos veículos de comunicação",
    editorial: "Política",
    excerpt:
      "Poder Executivo e Legislativo destacam o papel do jornalismo responsável para o desenvolvimento local.",
    href: "/colunistas/da-redacao",
  },
  {
    title: "Pesquisa popular sobre desempenho da Câmara em 2025",
    editorial: "Notícias",
    excerpt:
      "Enquete aberta para avaliação da população sobre projetos de lei e destaque parlamentar.",
    href: "/#enquete",
  },
];
